### ISSUE TITLE
update deployment script for ubuntu server 18

### ISSUE THREAD

**Issue by pradikta** [pt-studio/openstack-queens-labs#1]
this script needs to be customized to support ubuntu 18 server especially for ip settings, where in ubuntu 18 use netplan

**Comment by tienthanh2509** [comment]
yes, you need to configure IP manual at the moment
I am working on new script work with Ubuntu Bionic Beaver and it is under testing
It will release soon

**Comment by pradikta** [comment]
I has been try your script on ubuntu 16, There is some error in nova installation section that cause nova could not installed, after i check the script, i found some diferrent command and setting compared with openstack queen version deployment(instalation) guide on openstack official site.  I hope there will be improvements and adjustments with the latest version and Hopefully it will be released as soon as possible. Your script is helpfull, Thank you

**Comment by tienthanh2509** [comment]
Since current script missing update auth url for nova service, nova will can't contact to keystone

**Comment by pradikta** [comment]
Yes that's exactly the problem, do you have solution?

**Comment by tienthanh2509** [comment]
It already fixed at local work, I will merge it soon

**Comment by pradikta** [comment]
Should I use 3 networks, is it possible if I have only 2 networks?

**Comment by tienthanh2509** [comment]
In the official devstack u can use only one or 2 ethernet card. But in this repo already separate into 3 tier network.

**Comment by tienthanh2509** [comment]
Fixed c24c0e8469d693f841f0b6eb5152ec917e3b162e

https://github.com/pt-studio/openstack-queens-labs/blob/master/scripts/install/04_neutron.sh#L212
