### ISSUE TITLE
setup02.sh error

### ISSUE THREAD

**Issue by pradikta** [pt-studio/openstack-queens-labs#2]
./setup02.sh: line 12: /root/openstack/scripts/lib/base.sh: No such file or directory

file not found in the folder

**Comment by tienthanh2509** [comment]
Please checkout again dcce894a1cb43924cc9ff0dec9e1addaa9f21211

**Comment by pradikta** [comment]
setup02.sh running well but still error on setup03.ssh
./setup03.sh: line 12: /root/openstack/scripts/admin-openrc: No such file or directory

**Comment by tienthanh2509** [comment]
I just recheck again and fixed ;)

**Comment by pradikta** [comment]
take your time, thank you 👍

**Comment by pradikta** [comment]
one more in read me file show ./create-vm.sh, but in folder not found.

**Comment by tienthanh2509** [comment]
If nova stuck in "Boot from hard disk..."
 please workaround by change `/etc/nova/nova-compute.conf`
like this

```
[DEFAULT]
compute_driver=libvirt.LibvirtDriver
[libvirt]
virt_type=qemu
cpu_mode=none

```
`one more in read me file show ./create-vm.sh, but in folder not found.` use test_*.sh instead
`test_cinder.sh` > `test_neutron.sh` > `test_nova_*.sh`
